---
title: "Covid gif"
author: "Tony"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(tidyverse)
library(ggplot2)
library(gganimate)
library(viridis)
library(gifski)
```


```{r read data, fig.width=10}
# import data
covid <- read_csv("../data/covid_tidy.csv")
# theme covid
theme_covid <- function(...) {
  theme_minimal() +
  theme(
    # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", color = NA), 
    panel.background = element_rect(fill = "white", color = NA), 
    legend.background = element_rect(fill = "white", color = NA),
    panel.border = element_blank(),
    ...
  )
}
# generate gif file
covid %>%
  # tidy data
  pivot_longer(cols = c(case_count, death_count), names_to = "count", values_to = "number") %>%
  arrange(date) %>% # arrange by date
  ggplot(aes(x = date, y = number, color = count)) +
  geom_line(size = 3) +
  geom_point() +
  facet_wrap(~count, scales = "free") +
  theme_covid() +
  labs(title = "Covid-19 case & death count",
  x = "Date", 
  y = "Number of people") +
  scale_color_manual( values =  c("darkorange", "darkorchid4")) +
  transition_reveal(date) -> covid_ani

animate(covid_ani, duration = 10,fps = 20, width =1500, height = 300, renderer = gifski_renderer())
anim_save("figs/covid.gif")
```