---
title: "data_processing"
output: html_document
---

```{r library, message=F, warning=F}
library(tidyverse)
library(dplyr)
library(knitr)
library(lubridate)
library(zoo)

## Install the required package with:
## install.packages("RSocrata")

library(RSocrata) # Read data from NYC OpenData
```

```{r read_datar, message=F, warning=F}
# Read data set online
homeless <- read.socrata(
  "https://data.cityofnewyork.us/resource/ur7y-ziyb.json",
  app_token = "IKAeRZx0jHfj8qD1SvDGxHGsx",
  email     = "hz2694@columbia.edu",
  password  = "9N6nrWC*y5#3zwG"
)

covid <- read.socrata(
  "https://data.cityofnewyork.us/resource/rc75-m7u3.json",
  app_token = "IKAeRZx0jHfj8qD1SvDGxHGsx",
  email     = "hz2694@columbia.edu",
  password  = "9N6nrWC*y5#3zwG"
)

shelters <-  read.socrata(
  "https://data.cityofnewyork.us/resource/bmxf-3rd4.json",
  app_token = "IKAeRZx0jHfj8qD1SvDGxHGsx",
  email     = "hz2694@columbia.edu",
  password  = "9N6nrWC*y5#3zwG"
)
```

```{r data_process, message = F, warning = F}
# There is only one case for covid in 2020 Feb, hence we chose data after 2020/03/01
homeless %>%
  mutate(across(individuals, ~ ifelse(is.na(.), 0, .))) %>%  # remove na (if needed)
  mutate(count = as.numeric(individuals)) %>%
  select(date = report_date, borough, community_district, count) %>%
  filter(date >= as.Date("2020-03-01")) -> homeless_tidy # after 2020/03/01 (covid period)

# Processing with community district (interactive area)
# We divide count by each special CD in the borough
# 164 Central Park, 226 Van Cortlandt Park 227 Bronx Park 228 Pelham Bay Park
# 355 Prospect Park 356 Brooklyn Gateway National Recreational Area
# 480 LaGuardia Airport 481 Flushing Meadow/Corona Park 482 Forest Park
# 483 JFK International Airport 484 Queens Gateway National Recreational Area
# 595 Staten Island Gateway National Recreational Area

homeless_tidy %>% # Filter district with unkown CD
  filter(community_district == "Unknown CD") %>%
  mutate(community_district = ifelse(borough == "Bronx", "26",
                               ifelse(borough == "Brooklyn", "55",
                               ifelse(borough == "Manhattan", "16",
                               ifelse(borough == "Queens", "82", "95"))))) -> df

df %>%
  filter(borough == "Bronx") %>%
  mutate(count = count / 3) -> Bronx_1

Bronx_1 %>%
  mutate(community_district = 27) -> Bronx_2

Bronx_1 %>%
  mutate(community_district = 28) -> Bronx_3

df %>%
  filter(borough == "Brooklyn") %>%
  mutate(count = count / 2) -> Brooklyn_1

Brooklyn_1 %>%
  mutate(community_district = 56) -> Brooklyn_2

df %>%
  filter(borough == "Queens") %>%
  mutate(count = count / 5) -> Queens_1

Queens_1 %>%
  mutate(community_district = 80) -> Queens_2

Queens_1 %>%
  mutate(community_district = 81) -> Queens_3

Queens_1 %>%
  mutate(community_district = 83) -> Queens_4

Queens_1 %>%
  mutate(community_district = 84) -> Queens_5

df %>%
  filter(borough == "Manhattan") -> Manhattan

df %>%
  filter(borough == "Staten Island") -> Staten_Island

Bronx_1 %>%
  rbind(Bronx_2, Bronx_3, Brooklyn_1, Brooklyn_2, Queens_1, Queens_2,
        Queens_3, Queens_4, Queens_5, Manhattan, Staten_Island) %>%
  arrange(community_district) -> h
 

homeless_tidy %>% # Fills with interactive area code
  filter(community_district != "Unknown CD") %>%
  rbind(h) %>%
  arrange(date, borough) %>%
  mutate(community_district = as.numeric(community_district)) %>%
  mutate(borough_code = ifelse(borough == "Bronx", 2,
                               ifelse(borough == "Brooklyn", 3,
                               ifelse(borough == "Manhattan", 1,
                               ifelse(borough == "Queens", 4, 5))))) %>%
  mutate(BoroCD = ifelse(community_district <10, paste(borough_code, 0, community_district, sep = ""),
                         paste(borough_code, community_district, sep = ""))) -> homeless_tidy

# save files
write.csv(homeless_tidy, "../data/homeless_tidy.csv", row.names = FALSE)

covid %>%
  select(date = date_of_interest, case_count, death_count) %>%
  mutate(case_count = as.numeric(case_count),
         death_count = as.numeric(death_count)) %>%
  filter(date >= as.Date("2020-03-01")) %>%              # after 2020/03/01 (covid period)
  transform(month_year = as.numeric(format(as.Date(date), "%m%y"))) %>%  
  group_by(month_year) %>%  # calculate total cases by month
  summarise(case_count = sum(case_count), death_count = sum(death_count)) %>% # calculate total cases   
  mutate(date = ceiling_date(my(month_year), unit = "month") - 1) %>% 
  # transform the first day of month to the last day of month
  select(date, case_count, death_count) -> covid_tidy

# save files
write.csv(covid_tidy, "../data/covid_tidy.csv", row.names = FALSE)

shelters %>%
  select(name = center_name, borough, address, postcode:council_district) -> shelters_tidy

# save files
write.csv(shelters_tidy, "../data/shelters_tidy.csv", row.names = FALSE)
```

```{r combine_data, message=F, warning=F}
# Combine our data set
homeless_tidy %>%  # combine data set
  left_join(covid_tidy, date = date) -> homeless_covid

# save files
write.csv(homeless_covid, "../data/homeless_covid.csv", row.names = FALSE)
```