---
title: "map"
author: "Tony"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(rworldmap)
library(rgdal)
library(ggplot2)
```

```{r read_data, message=F, warning=F}
homeless_tidy <- read.csv("../data/homeless_tidy.csv")
homeless_tidy %>%
  filter(community_district == "Unknown CD") %>%
  mutate(community_district = ifelse(borough == "Bronx", "26",
                               ifelse(borough == "Brooklyn", "55",
                               ifelse(borough == "Manhattan", "16",
                               ifelse(borough == "Queens", "82", "95"))))) -> df
homeless_tidy %>%
  filter(community_district != "Unknown CD") %>%
  rbind(df) %>%
  arrange(date, borough) %>%
  mutate(community_district = as.numeric(community_district)) %>%
  mutate(borough_code = ifelse(borough == "Bronx", 2,
                               ifelse(borough == "Brooklyn", 3,
                               ifelse(borough == "Manhattan", 1,
                               ifelse(borough == "Queens", 4, 5))))) %>%
  mutate(BoroCD = ifelse(community_district <10, paste(borough_code, 0, community_district, sep = ""),
                         paste(borough_code, community_district, sep = ""))) -> homeless_join
```

```{r map, message=F, warning=F}
# worldMap <- getMap(resolution = "high")
# country <- c("United States")
# ind <- which(worldMap$NAME %in% country)

nycd <- "../data/nycd_21d/nycd.shp"
# nycdwi <- "../data/nycdwi_21d/nycdwi.shp"
nycd_shp <- readOGR(dsn = nycd, stringsAsFactors = F)
# nycdwi_shp <- readOGR(dsn = nycdwi, stringsAsFactors = F)
nycd_map <- ggplot() +
  geom_polygon(data = nycd_shp, aes(x = long, y = lat, group = group), colour = "black", fill = NA)
# nycdwi_map <- ggplot() +
#   geom_polygon(data = nycdwi_shp, aes(x = long, y = lat, group = group), colour = "black", fill = NA)
nycd_map + theme_void()
# nycdwi_map + theme_void()
```